### ISSUE TITLE
Error on ‘wicg init "Whisky API"’

### ISSUE THREAD

**Issue by MichielBijl** [WICG/starter-kit#5]
I get an error when I run:

```
wicg init "Whisky API"
```

Terminal spits back:

```
/usr/local/lib/node_modules/wicg/index.js:12
const { version } = require("./package.json");
      ^

SyntaxError: Unexpected token {
    at exports.runInThisContext (vm.js:53:16)
    at Module._compile (module.js:373:25)
    at Object.Module._extensions..js (module.js:416:10)
    at Module.load (module.js:343:32)
    at Function.Module._load (module.js:300:12)
    at Function.Module.runMain (module.js:441:10)
    at startup (node.js:139:18)
    at node.js:974:3
```

I run node v4.5.0

**Comment by alvestrand** [comment]
This is the same problem I reported in #4 - when you install with a node version less than 6, the error message doesn't make it obvious that this is the problem.

**Comment by MichielBijl** [comment]
Aye, Robin Berjon notified me on the list. Have updated and it now works.

Thanks 👍

**Comment by marcoscaceres** [comment]
@MichielBijl, great to hear. Excited about the Whisky API. Would drink again! A++++
