### ISSUE TITLE
ERR_REQUIRE_ESM

### ISSUE THREAD

**Issue by ArthurSonzogni** [WICG/starter-kit#66]
I tried this for the first time:
```bash
wicg init "My Awesome API"
internal/modules/cjs/loader.js:1015
      throw new ERR_REQUIRE_ESM(filename, parentPath, packageJsonPath);
      ^

Error [ERR_REQUIRE_ESM]: Must use import to load ES Module: /usr/local/lib/node_modules/wicg/node_modules/chalk/source/index.js
require() of ES modules is not supported.
require() of /usr/local/lib/node_modules/wicg/node_modules/chalk/source/index.js from /usr/local/lib/node_modules/wicg/messages.js is an ES module file as it is a .js file whose nearest parent package.json contains "type": "module" which defines all .js files in that package scope as ES modules.
Instead rename index.js to end in .cjs, change the requiring code to use import(), or remove "type": "module" from /usr/local/lib/node_modules/wicg/node_modules/chalk/package.json.

    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1015:13)
    at Module.load (internal/modules/cjs/loader.js:863:32)
    at Function.Module._load (internal/modules/cjs/loader.js:708:14)
    at Module.require (internal/modules/cjs/loader.js:887:19)
    at require (internal/modules/cjs/helpers.js:74:18)
    at Object.<anonymous> (/usr/local/lib/node_modules/wicg/messages.js:2:15)
    at Module._compile (internal/modules/cjs/loader.js:999:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1027:10)
    at Module.load (internal/modules/cjs/loader.js:863:32)
    at Function.Module._load (internal/modules/cjs/loader.js:708:14) {
  code: 'ERR_REQUIRE_ESM'
}
```

I believe the error is caused by [upgrading](https://github.com/WICG/starter-kit/commit/4fbd0cbc0edff9a4ecaa6041b18d07fa59981b59) "chalk" to 5.0.0. It introduced a breaking change about using module.

This is similar to:
https://stackoverflow.com/questions/70309135/chalk-error-err-require-esm-require-of-es-module

**Comment by yoavweiss** [comment]
Hmm, thanks for filing an issue!

/cc @marcoscaceres - Are you aware of the `chalk` upgrade and its reasoning?

**Comment by ysulyma** [comment]
just encountered this as well

**Comment by marcoscaceres** [comment]
Should be fixed by https://github.com/WICG/starter-kit/pull/77/
